export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOAD_ERROR = "LOAD_ERROR";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const ADD_ACTOR_SUCCESS = "ADD_DOCTOR_SUCCESS";
export const ADD_ACTOR_FAILURE = "ADD_DOCTOR_FAILURE";
