export const SET_SCHEDULE = "SET_SCHEDULE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOAD_ERROR = "LOAD_ERROR";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const ADD_ACTOR_SUCCESS = "ADD_DOCTOR_SUCCESS";
export const ADD_ACTOR_FAILURE = "ADD_DOCTOR_FAILURE";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS";
export const UPDATE_SCHEDULE_FAILURE = "UPDATE_SCHEDULE_FAILURE";

export const SET_WIDTH = "SET_WIDTH";
export const SET_HEIGHT = "SET_HEIGHT";
export const SET_IS_MOBILE = "SET_IS_MOBILE";
export const SET_IS_NOT_MOBILE = "SET_IS_NOT_MOBILE";
