export const SET_DOCTOR_SCHEDULE_SUCCESS = "SET_DOCTOR_SCHEDULE_SUCCESS";
export const SET_DOCTOR_SCHEDULE_FAILURE = "SET_DOCTOR_SCHEDULE_FAILURE";
export const SET_COMPOUNDER_SCHEDULE_SUCCESS =
  "SET_COMPOUNDER_SCHEDULE_SUCCESS";
export const SET_COMPOUNDER_SCHEDULE_FAILURE =
  "SET_COMPOUNDER_SCHEDULE_FAILURE";
export const SET_AVAILABLIITY_SUCCESS = "SET_AVAILABLIITY_SUCCESS";
export const SET_AVAILABLIITY_FAILURE = "SET_AVAILABLIITY_FAILURE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOAD_ERROR = "LOAD_ERROR";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const ADD_ACTOR_SUCCESS = "ADD_DOCTOR_SUCCESS";
export const ADD_ACTOR_FAILURE = "ADD_DOCTOR_FAILURE";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS";
export const UPDATE_SCHEDULE_FAILURE = "UPDATE_SCHEDULE_FAILURE";
export const UPDATE_AVAILABILITY_FAILURE = "UPDATE_AVAILABILITY_FAILURE";

export const SET_WIDTH = "SET_WIDTH";
export const SET_HEIGHT = "SET_HEIGHT";
export const SET_IS_MOBILE = "SET_IS_MOBILE";
export const SET_IS_NOT_MOBILE = "SET_IS_NOT_MOBILE";

export const GET_RELATIVES_SUCCESS = "GET_RELATIVES_SUCCESS";
export const GET_RELATIVES_FAILURE = "GET_RELATIVES_FAILURE";
export const ADD_RELATIVE_SUCCESS = "ADD_RELATIVE_SUCCESS";
export const ADD_RELATIVE_FAILURE = "ADD_RELATIVE_FAILURE";
export const UPDATE_RELATIVE_SUCCESS = "UPDATE_RELATIVE_SUCCESS";
export const UPDATE_RELATIVE_FAILURE = "UPDATE_RELATIVE_FAILURE";
export const DELETE_RELATIVE_SUCCESS = "DELETE_RELATIVE_SUCCESS";
export const DELETE_RELATIVE_FAILURE = "DELETE_RELATIVE_FAILURE";

export const GET_MEDICINE_SUCCESS = "GET_MEDICINE_SUCCESS";
export const GET_MEDICINE_FAILURE = "GET_MEDICINE_FAILURE";
export const GET_STOCKS_SUCCESS = "GET_STOCKS_SUCCESS";
export const GET_STOCKS_FAILURE = "GET_STOCKS_FAILURE";
export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS";
export const ADD_STOCK_FAILURE = "ADD_STOCK_FAILURE";
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS";
export const UPDATE_STOCK_FAILURE = "UPDATE_STOCK_FAILURE";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";
export const DELETE_STOCK_FAILURE = "DELETE_STOCK_FAILURE";
